### PR TITLE
Fix Mimick for aarch64

### LINKED ISSUE #9: Tests fail on Ubuntu 20.04 aarch64
### System details

- OS: Linux 5.4.0-1015
- Distribution: Ubuntu Focal 20.04
- CPU Architecture: `aarch64`
- Build tools:
   - `cmake` 3.16.3
   - `gcc` 9.3.0
   - `ld` 2.34

### Bug report

Tests fail because Mimick fails to inject the mock in the right place. [ELF support](https://github.com/Snaipe/Mimick/blob/7681d1ee8e0bffff806751092947648a6bebff24/src/plt-elf.c#L248) first checks for the `fn_vv` symbol in the `.rela.dyn` section and only goes look for it in the `.rela.plt` section if it fails the first lookup. I can see the `mmk_test` executable shows two relocations for that symbol, one in each table. 

```
Relocation section '.rela.dyn' at offset 0x1670 contains 24 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
...
000000022f60  000900000401 R_AARCH64_GLOB_DA 0000000000000000 fn_vv + 0
...
000000022f78  000c00000401 R_AARCH64_GLOB_DA 0000000000000000 fn_ii + 0
000000022f80  000d00000401 R_AARCH64_GLOB_DA 0000000000000000 fn_ii_va + 0
...
Relocation section '.rela.plt' at offset 0x18b0 contains 18 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
...
000000023020  000900000402 R_AARCH64_JUMP_SL 0000000000000000 fn_vv + 0
000000023030  000c00000402 R_AARCH64_JUMP_SL 0000000000000000 fn_ii + 0
000000023038  000d00000402 R_AARCH64_JUMP_SL 0000000000000000 fn_ii_va + 0
...
```

Stepping through machine code, I can see `Mimick` puts the mock trampoline in the GOT but trampolines in code use the PLT's GOT.

### Discussion

I failed to find a concise and complete explanation out there as to why two relocations are showing in my `aarch64` box. My recollection so far is that, in the most general case, a dynamic ELF executable needs both an `R_<ARCH>_JUMP_SLOT` relocation in the `.rela.plt` section for lazy binding of an external callable symbol and an `R_<ARCH>_GLOB_DAT` relocation in the `.rela.dyn` section when/if the address of an external callable symbol is requested (i.e. the function pointer). And while some linkers may perform an optimization and deduplicate this information, they are not bound to do so. 

@Snaipe does that sound reasonable? I can see [`plt_get_offsets()`](https://github.com/Snaipe/Mimick/blob/7681d1ee8e0bffff806751092947648a6bebff24/src/plt-elf.c#L265) is capable of returning multiple offsets. Did you intend to support such cases?

### PR DESCRIPTION
**Pull request by hidmic**
Closes #9. I found some other details in ELF support (e.g. not using the right `.rela.dyn` size) and an obscure one that seems specific to `aarch64`: CPU caches must be flushed after flipping page protection bits.

### CODE REVIEW

File: src/plt-elf.c [hunk 1]
```diff
@@ -224,54 +223,62 @@ static uintptr_t get_offset(struct rel_info *info, ElfW(Sym) *symtab,
...
+  {
+    .tab = rel,
+    .size = rel_sz,
+    .entry_sz = relent_sz,
+  },
+  {
+    .tab = jmprel,
+    .size = jmprel_sz,
+    .entry_sz = relent_sz,
+  }};
```
Comment (Snaipe) [inline src/plt-elf.c:261]: nit: reformat to:

```
struct rel_info info[] = {
    {
        .tab = rel,
        .size = rel_sz,
        .entry_sz = relent_sz,
    },
    {
        .tab = jmprel,
        .size = jmprel_sz,
        .entry_sz = relent_sz,
    }
};
```

File: src/plt-elf.c [hunk 2]
```diff
@@ -224,54 +223,62 @@ static uintptr_t get_offset(struct rel_info *info, ElfW(Sym) *symtab,
...
+    if (off) {
+      if (offsets) {
+        *offsets = mmk_realloc(*offsets, (n + 1) * sizeof(plt_offset));
+        (*offsets)[n] = (plt_offset) { .offset = (plt_fn **)(base + off) };
+      }
+      ++n;
+    }
+  }
+
+  return n;
```
Comment (Snaipe) [inline src/plt-elf.c:274]: Please use 4-space indents.

File: src/plt-elf.c [hunk 3]
```diff
@@ -195,9 +195,8 @@ plt_lib plt_get_lib(plt_ctx ctx, const char *name)
             if (!strcmp(name, libname))
                 return lm;
         } else if (sel == PLT_SEL_SYM) {
-            plt_fn **sym = plt_get_offset(ctx, lm, val);
-            if (sym)
-                return lm;
+          if (get_offsets(ctx, lm, val, NULL) > 0)
```
Comment (Snaipe) [inline src/plt-elf.c:198]: nit: 4-space indent

File: src/plt-elf.c [hunk 4]
```diff
@@ -224,54 +223,62 @@ static uintptr_t get_offset(struct rel_info *info, ElfW(Sym) *symtab,
...
-    if (off) {
-        plt_offset *ot = mmk_malloc(sizeof (plt_offset));
-        *n = 1;
-        *ot = (plt_offset) { .offset = off };
-        return ot;
-    }
-    return NULL;
+    plt_offset *ot = NULL;
+    *n = get_offsets(ctx, lib, name, &ot);
+    return ot;
```
Comment (Snaipe) [inline src/plt-elf.c:281]: Since `plt_get_offsets` pretty much just becomes useless, I would just rename `get_offsets` to `plt_get_offsets` and have it return the allocated offset array rather than retrieving it by pointer.

File: src/trampoline.c [hunk 5]
```diff
@@ -73,7 +77,12 @@ plt_fn *create_trampoline(void *ctx, plt_fn *routine)
     *map = ctx;
     *(map + 1) = (void *) routine;
     memcpy(map + 2, mmk_trampoline, trampoline_sz);
-    mprotect(map, PAGE_SIZE, PROT_READ | PROT_EXEC);
+    mmk_assert(!mprotect(map, PAGE_SIZE, PROT_READ | PROT_EXEC));
+# if defined __clang__  // Check for Clang first, it may set __GNUC__ too.
+    __clear_cache(map, map + PAGE_SIZE);
+# elif defined __GNUC__
+    __builtin___clear_cache((char *)map, (char *)(map + PAGE_SIZE));
+# endif
```
Comment (Snaipe) [inline src/trampoline.c:85]: Interesting. Do you know why clearing the cache is necessary?

The mprotect in `plt_set_offsets` didn't seem to crash, is a cache clear not necessary in that function? This is weird.

File: src/plt-elf.c (hunk 4 above)
Comment (hidmic) [reply src/plt-elf.c:281]: I could, but `plt_get_lib` still needs a way check for symbol existence [here](https://github.com/Snaipe/Mimick/blob/7681d1ee8e0bffff806751092947648a6bebff24/src/plt-elf.c#L198) and I'd rather not incur in a memory allocation if there's no use for it. Thus this two functions. WDYT?

File: src/trampoline.c (hunk 5 above)
Comment (hidmic) [reply src/trampoline.c]: > Interesting. Do you know why clearing the cache is necessary?
>
> The mprotect in `plt_set_offsets` didn't seem to crash, is a cache clear not necessary in that function? This is weird.

So, not clearing caches does not consistently make the library crash. I have not had issues with Mimick as-is on `amd64`. But on `aarch64` I'd get a SIGILL somewhere within the trampoline ([here](https://github.com/Snaipe/Mimick/blob/7681d1ee8e0bffff806751092947648a6bebff24/src/asm/trampoline-aarch64.S#L27) and [here](https://github.com/Snaipe/Mimick/blob/7681d1ee8e0bffff806751092947648a6bebff24/src/asm/trampoline-aarch64.S#L68), for instance). I was initially suspicious about `mprotect`. Eventually I found out that [`glibc` does flush caches](https://github.com/bminor/glibc/blob/master/elf/dl-reloc.c#L294) when bringing in a shared library code into memory space. I can't tell for sure, but I suspect it's the instruction cache that's causing problems when flipping page protection bits.

> The mprotect in plt_set_offsets didn't seem to crash, is a cache clear not necessary in that function?

Uh, I missed that one. Also, `mmk_mprotect` should be used here and not `mprotect`. See https://github.com/Snaipe/Mimick/pull/10/commits/edd0150e328c2630f0ac5eef0f546ff1ec291a07.

File: src/plt-elf.c (hunk 1 above)
Comment (hidmic) [reply src/plt-elf.c]: Done in https://github.com/Snaipe/Mimick/pull/10/commits/a275442693bc5e4c8f8ba537313ed0d4834c0ca0.

File: src/plt-elf.c (hunk 2 above)
Comment (hidmic) [reply src/plt-elf.c]: Done in https://github.com/Snaipe/Mimick/pull/10/commits/a275442693bc5e4c8f8ba537313ed0d4834c0ca0.

File: src/plt-elf.c (hunk 3 above)
Comment (hidmic) [reply src/plt-elf.c]: Done in https://github.com/Snaipe/Mimick/pull/10/commits/a275442693bc5e4c8f8ba537313ed0d4834c0ca0.

File: src/plt-elf.c (hunk 4 above)
Comment (Snaipe) [reply src/plt-elf.c:286]: Ah, I see. That makes sense, this is fine as-is.

**Comment by hidmic** [comment]
> so would you mind adding a paragraph or two describing what you explained to me in your comment in the commit message body (including how you discovered that glibc was in fact doing this)?

Sure. I'll rebase so we get a clean history.
